remote_theme: coursweb/jk-theme
title: EEDEV 2 - ID311
description: Cours Projet Interface
lang: fr-FR
# markdown: GFM
robots: noindex, nofollow
# menu 
chapters:
 - title: Cours Dev 2
   url: https://code.eracom-pedagogique.ch/eedev2-id311/
 - title: Référence CSS
   url: https://cours-web.ch/css/
 - title: Infos IMD
   url: https://eracom.ch/informations-eleves-id/
# - title: Plan de formation
#   url: https://code.eracom-pedagogique.ch/formation-imd-2020/   
# - title: Fontes IMD
#   url: https://code.eracom-pedagogique.ch/fontes-imd/  
 - title: Figma
   url: https://www.figma.com/files/team/1010489491753002544
# - title: 🧠 Podsie
#   url: https://student.podsie.org/
# pied de page   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom/eedev2-id311">Lien Github</a></li></ul>
